### ISSUE TITLE
Loading async data guide is outdated

### ISSUE THREAD

**Issue by LabiKyo** [router5/router5.github.io#17]
Hi, thanks for your work, router5 is really good.

I'm trying to migrate from react-router-redux to redux-router5. Seems like the async data guide last updated during v1.0, now middleware don't have access to `route` which I don't know what it is. Can I still have access to RouteNode's props like `onActivate` or any other customize prop? Any advice would be nice!

**Comment by troch** [comment]
Hi @LabiKyo,

I don't believe the guide is outdated. By `route` I guess you refer to `routes`, it is just a closure on my routes configuration. When I define a middleware with that signature, it is in fact a middleware "creator" (it returns a function which can be used as a middleware):

``` js
const dataMiddleware = routes => ...
```

I use it like this

``` js
router.useMiddleware(dataMiddleware(routes));
```

It is the same for redux. `routes` is what I pass both to the router (adding routes) and to the middleware "creator". The router pass it down to `RouteNode`, but `RouteNode` is only interested in `name` and `path` (`canActivate` is used by the router if the route is added successfully, but `onActivate` would simply be ignored).

**Comment by LabiKyo** [comment]
I see! That make sense, only the name of middleware is a bit confusing. Sorry to bother you. :P

**Comment by troch** [comment]
No problem, I'll add a note to make it clearer

**Comment by troch** [comment]
No problem, I'll keep it in mind when I update the docs to make it a bit clearer.
